### ISSUE TITLE
Support XDG Base Directory Spectre

### ISSUE THREAD

**Issue by alichtman** [curusarn/resh#140]
It would be great if the data file was stored in an XDG compliant way.

**Comment by micnncim** [comment]
@curusarn Are you up for this idea? If so, I'd like to implement this.

**Comment by curusarn** [comment]
Fixed in #184

Sorry for not taking you up on this. I do appreciate your offer.
Any changes that change how Resh interacts with the rest of the system are tricky because updating Resh from any previous version to current version needs to always work - e.g. history and configs need to be discovered and moved to new locations. And this discovery logic needs to stay in the installation forever because people can be running old Resh versions for a long time.

This is why I was hesitant to hand this over to someone else. Now I have implemented this as part of a bigger update where I'm adding an "update mechanisms" to installation which handles the location changes.
