### ISSUE TITLE
Limited history in bash

### ISSUE THREAD

**Issue by samuelhwilliams** [curusarn/resh#150]
I've been using resh for a few months now and it's been great. However, recently I've noticed that some commands I haven't used in a long while have stopped showing up in resh search despite being in resh history. It seems like when they fall out of `.bash_history`, they aren't visible in resh search, despite them having entries in `.resh_history.json`. Is that intended?

My bash history size is limited to 500 lines but my resh history is 6k, and seems to have records of all the commands I've been searching for. Do I just need to make my bash history unlimited as well? It feels a bit redundant.

**Comment by curusarn** [comment]
Hi, sorry for the long silence.

This is very weird. Resh search should be definitely able to find any history entry from `.resh_history.json`. It loads the entire `.resh_history.json`.

----

I'm trying to replicate the issue - this is what i tried:

1. changed the very first command in `resh_history.json` to something unique:
```
❯ nvim ~/.resh_history.json
```
*display the line*
```
❯ head ~/.resh_history.json -n 1 | jq .cmdLine -r
echo this is the very first line in my resh history
```
*check if it is actually unique*
```
❯ grep "this is the very first" ~/.resh_history.json
{"cmdLine":"echo this is the very first line in my resh history","exitCode":0,"shell":"bash","uname":"Linux","sessionId":"d5c0fe70-c80b-4715-87cb-f8d8d5b4c673","home":"/home/simon","lang":"en_US.UTF-8","lcAll":"","login":"simon","pwd":"/home/simon","pwdAfter":"/home/simon","shellEnv":"/bin/bash","term":"xterm-256color","realPwd":"/home/simon","realPwdAfter":"/home/simon","pid":14560,"sessionPid":14560,"host":"simon-pc","hosttype":"x86_64","ostype":"linux-gnu","machtype":"x86_64-pc-linux-gnu","shlvl":1,"timezoneBefore":"+0200","timezoneAfter":"+0200","realtimeBefore":1566762905.173595,"realtimeAfter":1566762905.1894295,"realtimeBeforeLocal":1566770105.173595,"realtimeAfterLocal":1566770105.1894295,"realtimeDuration":0.015834569931030273,"realtimeSinceSessionStart":1.7122540473937988,"realtimeSinceBoot":20766.542254047396,"gitDir":"","gitRealDir":"","gitOriginRemote":"","gitDirAfter":"","gitRealDirAfter":"","gitOriginRemoteAfter":"","machineId":"c70365240bc647f09e2490722cc8186b","osReleaseId":"manjaro","osReleaseVersionId":"","osReleaseIdLike":"arch","osReleaseName":"Manjaro Linux","osReleasePrettyName":"Manjaro Linux","reshUuid":"","reshVersion":"1.1.1","reshRevision":"752acb916f2a","partsMerged":false,"recalled":false,"recallLastCmdLine":"","cols":"80","lines":"24"}
```


2. killed `resh-daemon` so that it loads the changed history:
```
❯ pkill resh-daemon 

resh-postcollect ERROR: 2020/08/02 13:10:40 resh-daemon is not running - try restarting this terminal
```

3. launched a new terminal to start up the daemon again

4. tried to search for the history entry and found it (the first result matches and it is 11 months old)

![Screenshot from 2020-08-02 13-17-58](https://user-images.githubusercontent.com/10132717/89121816-9b272800-d4c2-11ea-9590-02ef2856a3fc.png)

This shows that old records are being loaded (at least on my machine). Could you try something similar on your machine?
So there must be more than the size of the resh history causing the issue.

----

Things that come to mind:

- To make resh useful even right after installation resh-daemon loads `~/.bash_history` and `~/.zsh_history` if there is less than 2000 records in the `resh_history.json`.
- Does the issue go away if you kill `resh-daemon` and launch it again by opening a new terminal?  
- When resh searches and shows the results it deduplicates the records based on the "command with arguments" so maybe the deduplication could be broken which would result in some records being hidden. (unlikely but possible)
- Records with non-zero exit status are penalized and don't show up near the top. This can sometimes unexpectedly hide records because e.g. killing a command results in a non-zero exit status. Can you check if you can find the desired record if you make the query more specific?

**Comment by curusarn** [comment]
So, this didn't show up in the resh search for some reason :thinking: 
```
{"cmdLine":"ssh slet@bastion.REDACTED.REDACTED2.com","exitCode":255,"shell":"zsh","uname":"Linux","sessionId":"4b180c29-5a43-49a8-a835-96cac91fc87d","recordId":"982daff8-c54a-428d-b58f-c31e89ee695d","home":"/home/simon","lang":"en_US.UTF-8","lcAll":"","login":"simon","pwd":"/home/simon/git/REDACTED3","pwdAfter":"/home/simon/git/REDACTED3","shellEnv":"/usr/bin/zsh","term":"xterm-256color","realPwd":"/home/simon/git/REDACTED3","realPwdAfter":"/home/simon/git/REDACTED3","pid":37471,"sessionPid":37471,"host":"simon-tmp","hosttype":"x86_64","ostype":"linux-gnu","machtype":"x86_64","shlvl":1,"timezoneBefore":"+0200","timezoneAfter":"+0200","realtimeBefore":1596560206.296636,"realtimeAfter":1596560209.3597648,"realtimeBeforeLocal":1596567406.296636,"realtimeAfterLocal":1596567409.3597648,"realtimeDuration":3.063128709793091,"realtimeSinceSessionStart":629840.146232605,"realtimeSinceBoot":726921.3362326049,"gitDir":"/home/simon/git/REDACTED3","gitRealDir":"/home/simon/git/REDACTED3","gitOriginRemote":"ssh://git@REDACTED4.git","gitDirAfter":"/home/simon/git/REDACTED3","gitRealDirAfter":"/home/simon/git/REDACTED3","gitOriginRemoteAfter":"ssh://git@REDACTED4.git","machineId":"96eb5eeed41c47aea75a5dc2f9f6b082","osReleaseId":"manjaro","osReleaseVersionId":"","osReleaseIdLike":"arch","osReleaseName":"Manjaro Linux","osReleasePrettyName":"Manjaro Linux","reshUuid":"e0758471-fc9a-4032-884e-bae896936890","reshVersion":"v2.7.8-1-g5a40913-DEV","reshRevision":"5a40913540f7","partsMerged":true,"recalled":false,"recallHistno":6,"recallStrategy":"bash_recent - history-search-{backward,forward}","recallActionsRaw":"|||arrow_up:|||arrow_up:|||arrow_up:|||arrow_up:|||arrow_up:|||arrow_up:|||arrow_up:","recallLastCmdLine":"ssh slet@bastion.REDACTED1.REDACTED2.com","cols":"211","lines":"56"}
```

**Comment by curusarn** [comment]
This issue is consistently happening to me for a while now. Which means that I both can debug and fix this and also I will be annoyed into doing so pretty soon.

So this is just a quick update to make clear that this is not forgotten. Sorry about not being more active - it has been a lot lately.

**Comment by samuelhwilliams** [comment]
Glad that you're getting this now as well. I've been having increasingly more issues with resh suggestions lately, and think it's partially down to this. :(

**Comment by curusarn** [comment]
Sorry for the long wait. The issue should be fixed in [v2.7.12](https://github.com/curusarn/resh/releases/tag/v2.7.12)

You should see all of your history in the search app after you run `reshctl update`.

**Comment by samuelhwilliams** [comment]
This seems worse ...


```
dit:~/git/$ reshctl update

Please report any issues you encounter to: https://github.com/curusarn/resh/issues

Looking for the latest release ...
 * Latest version: 2.7.12 (git tag: v2.7.12)

Downloading files ...
 * resh_2.7.12_checksums.txt
######################################################################### 100.0%##O#- #                                     ######################################################################### 100.0%
 * resh_2.7.12_darwin_amd64.tar.gz
######################################################################### 100.0%##O#- #                                     ######################################################################### 100.0%

Checking integrity ...
 * OK

Extracting downloaded files ...
 * OK

Checking your system ...
 * Login shell: bash - OK
 * Bash version: 5.0.18(1)-release - OK
 * Zsh version: 5.7.1 - OK
 * Nohup installed: OK

Creating directories ...
Copying files ...
Generating completions ...
Copying more files ...
Finishing up ...
pkill: signalling pid 873: Operation not permitted

All done!
Thank you for using RESH
Issues go here: https://github.com/curusarn/resh/issues
Ctrl+R launches the RESH SEARCH app
/Users/dit/.resh/rawinstall.sh: line 151: i: command not found
RESH INFO: New RESH shellrc script was loaded - if you encounter any issues please restart this terminal session.
dit:~/git/$
-bash: /tmp/resh_collect_last_run_out.txt: Permission denied
resh-collect ERROR:
-bash: /tmp/resh_collect_last_run_out.txt: Permission denied
resh-collect ERROR:
```

Every command is just throwing this error now?

**Comment by curusarn** [comment]
Sorry about that.

Can you try to update now? I just pushed a fix that should solve the error.

**Comment by samuelhwilliams** [comment]
Looks good, thanks!
