### ISSUE TITLE
resh messes with my starship prompt: it adds plus (+) to the start of it

### ISSUE THREAD

**Issue by honzajde** [curusarn/resh#175]
resh messes with my starship prompt: it adds plus (+) to the start of it
```
~/temp 
❯ date +%s.%N
1653026984.945819882

~/temp 
+  ❯ 
````

**Comment by honzajde** [comment]
Seems to be more related to starship than to resh. I have got rid of the problem by simplifying my starship configuration and also upgraiding starship.

**Comment by curusarn** [comment]
Some shell functions provided by Resh are run before and after commands are executed. This is how Resh records the command history with information like pwd, data, git repository, etc.

Running functions before and after commands is a bit hacky in bash which is why sometimes there can be weird interactions with other shell configuration. Especially, prompt customizations have a chance to interact with how Resh works.

I'm happy that you managed to resolve the issue.
