### ISSUE TITLE
Strange symbols in the history file

### ISSUE THREAD

**Issue by jakobkogler** [curusarn/resh#75]
Not sure how useful this bug report is, as I don't know how to replicate it. 

---

### Report
After a force-reboot of my machine, the `resh-daemon` didn't start any more.

```
>> echo Test
resh-collect ERROR: 2020/01/25 18:08:57 resh-daemon is not running :(
Test
resh-postcollect ERROR: 2020/01/25 18:08:57 resh-daemon is not running :(
```

Trying to start the daemon looked fine, but also didn't work.
```
>> resh-daemon
resh-collect ERROR: 2020/01/25 18:08:02 resh-daemon is not running :(
2020/01/25 18:08:02 Daemon starting...
version: 2.5.13 commit: 892b06453d3dc03f5a1bdd85a9adf2110a01183e
resh-postcollect ERROR: 2020/01/25 18:08:02 resh-daemon is not running :(
```
And in the `~/.resh/daemon.json` I found:
```
31112 | 2020/01/25 18:08:02 Error while checking daemon status - it's probably not running! Get http://localhost:2627/status: dial tcp [::1]:2627: connect: connection refused
31112 | 2020/01/25 18:08:02 Error while checking if the daemon is runnnig Get http://localhost:2627/status: dial tcp [::1]:2627: connect: connection refused
31112 | 2020/01/25 18:08:02 Pidfile exists
31112 | 2020/01/25 18:08:02 29030
31112 | 2020/01/25 18:08:02 Command finished with error: exit status 1
31112 | 2020/01/25 18:08:02 Error while killing daemon exit status 1
31112 | 2020/01/25 18:08:02 histfile: Checking if resh_history is large enough ...
31112 | 2020/01/25 18:08:02 histfile WARN: resh_history is too small - loading native bash and zsh history ...
31112 | 2020/01/25 18:08:02 histfile: bash history loaded - cmdLine count: 161
31112 | 2020/01/25 18:08:02 Open() zsh history file error: open /home/jakob/.zsh_history: no such file or directory
31112 | 2020/01/25 18:08:02 WARN: Skipping reading zsh history!
31112 | 2020/01/25 18:08:02 histfile: zsh history loaded - cmdLine count: 0
31112 | 2020/01/25 18:08:02 histfile: Loading resh history from file ...
31112 | 2020/01/25 18:08:02 Line:
31112 | 2020/01/25 18:08:02 Decoding error:invalid character '\x00' looking for beginning of value
```

### Solution: 

I opened the file `~/.resh_history.json` and saw that the last line contained strange binary symbols. (Sorry, I don't have them any more.) I removed this line, and now the daemon is able to start again.
Looks like something gone wrong when force-rebooting the machine.

**Comment by jakobkogler** [comment]
Actually I found the file. It was just a bunch of 0 bytes.

**Comment by curusarn** [comment]
Thanks for the report.


So just to sum up what has happened:

Force-rebooting (probably) while daemon was writing to the history file (`~/.resh_history.json`) resulted in the history file becoming invalid JSON. 
Invalid JSON history file prevented the daemon from starting because it couldn't decode it.



I'm wondering if I'm doing anything that is making this kind of error more likely. Maybe I could buffer the writes instead of writing history records as soon as possible.

The second thing that comes to mind is that I could work around this type of error during daemon start-up. This would be pretty simple because `~/.resh_history.json` is a file with one JSON on each line. When getting the JSON decoding error on the very end of the file I could ignore the error and get rid of invalid characters.

**Comment by curusarn** [comment]
This just happened to someone else. (https://github.com/curusarn/resh/issues/84)

**Comment by curusarn** [comment]
fixed in https://github.com/curusarn/resh/pull/85 (invalid history files is fixed dring daemon start up)

**Comment by curusarn** [comment]
@jakobkogler Hi, are you using Linux or macOS?

**Comment by jakobkogler** [comment]
@curusarn Linux. Current Manjaro version.
