### ISSUE TITLE
Time and date of last run

### ISSUE THREAD

**Issue by JosefBunes** [curusarn/resh#94]
Dear,

is possible to add the funcion to see the time and date of last run of (searched) commands?

https://imgur.com/LjfCO1X

ThX

**Comment by curusarn** [comment]
Sorry for the long silence, this is definitely a feature I will add later. 

Thanks for the suggestion!

**Comment by curusarn** [comment]
I'm currently experimenting with displaying date.
What do you think about relative time displayed like this:
![Screenshot from 2020-05-02 01-08-23](https://user-images.githubusercontent.com/10132717/80861246-90fc5000-8c6d-11ea-86fb-682c72e83423.png)

**Comment by curusarn** [comment]
this is what I'm experimenting with right now. 

larger terminal:
![Screenshot from 2020-05-07 16-00-20](https://user-images.githubusercontent.com/10132717/81303434-f7bda700-907b-11ea-92b7-a3c7194c4cb8.png)

compact date for smaller terminals:
![Screenshot from 2020-05-07 16-00-01](https://user-images.githubusercontent.com/10132717/81303436-f8eed400-907b-11ea-8295-bb1e0152f2ca.png)

**Comment by curusarn** [comment]
Small update on the date feature:
1) I'm happy with relative times because they are easier to read and they have short variants for small terminals
2) I have added the full date to the status line so you can see the exact date of the selected command

![Screenshot from 2020-05-09 21-14-22](https://user-images.githubusercontent.com/10132717/81482935-c17a5600-923a-11ea-81ca-95d543521204.png)
